@server = http://localhost:3000/auth
### register
POST {{server}}/register
Content-Type: application/json

{
    "email": "bbb@abc.com",
    "password": "bbb",
    "username": "bbb"
}

### login
POST {{server}}/login
Content-Type: application/json

{
    "email": "aaa@abc.com",
    "password": "aaa"
}

### login2
POST {{server}}/login2
Content-Type: application/json

{
    "email": "bbb@abc.com",
    "password": "bbb"
}

### Guard test
GET {{server}}/test-guard

### login3
POST {{server}}/login3
Content-Type: application/json

{
    "email": "bbb@abc.com",
    "password": "bbb"
}

### login3 wrong password
POST {{server}}/login3
Content-Type: application/json

{
    "email": "bbb@abc.com",
    "password": "bb"
}

### auth test
GET {{server}}/test-guard2